# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PhysOcean"); Pkg.test("PhysOcean"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("PhysOcean")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("PhysOcean")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push documentation to the github pages
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PhysOcean")); include(joinpath("docs", "make.jl"))'